apiVersion: v1
kind: Service
metadata:
  name: scs-backend
  namespace: scs-project
  labels:
    app: scs-backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: scs-backend