
services: 
  frontend:
    image: tuansondocker1407/capstone-sp-25-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  

  aspnet-api:
    image: tuansondocker1407/capstone-sp-25-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
      # The following volume is used to store the DataProtection-Keys
      - aspnet-api-data:/app/.aspnet/DataProtection-Keys
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend-network
    env_file:
      - .env  

  ai-service:
    image: tuansondocker1407/capstone-sp-25-ai-service
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend-network
    volumes:
      - ai-service-data:/app/app/models

  ai-service-agent:
    image: tuansondocker1407/capstone-sp-25-ai-service-agent
    build:
      context: ./ai_service_agent
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env  
    networks:
      - backend-network

  email-proxy:
    image: tuansondocker1407/email_proxy_mock:latest
    build:
      context: ./EmailProxyMock
      dockerfile: Dockerfile
    container_name: email-proxy
    ports:
      - "8001:8000"
    
networks:
  backend-network:
    driver: bridge

volumes:
  aspnet-api-data:
    name: aspnet-api-data
  ai-service-data:
    name: ai-service-data