apiVersion: v1
kind: Service
metadata:
  name: ai-service-agent
  namespace: scs-project
  labels:
    app: ai-service-agent
spec:
  selector:
    app: ai-service-agent
  ports:
  - port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
