apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: scs-project
type: Opaque
stringData:
  PUBLIC_ENV__META__GOOGLE_CLIENT_KEY: "your-google-client-key"
  META__CHECKSUM_KEY: "40612359b37772321b7"
  META__CHAT_BOT_KEY: "your-chat-bot-key"
  META__RECAPTCHA_KEY: "your-recaptcha-key"
