name: Unit Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      frontend_dir:
        required: true
        type: string
      backend_dir:
        required: true
        type: string

jobs:
  react-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    defaults:
      run:
        working-directory: ${{ inputs.frontend_dir }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'   
        cache-dependency-path: './Frontend/package.json'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run test:unit 


  dotnet-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run .NET Unit Tests
        run: |
          cd ${{ inputs.backend_dir }}
          dotnet test --verbosity normal
